server:
  port: 8080
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Tashkent
  datasource:
    username: webclubu_demo_bread
    url: jdbc:postgresql://localhost:5432/webclubu_demo_bread
    password: sardor
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
app:
  name: Demo Bread Shop
  version: 1.0