server:
  port: 8088
spring:
  profiles:
    active: spring.profiles.active
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Tashkent
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/bread_shop
    password: sardor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
app:
  name: Demo Bread Shop
  version: 1.0

#    #!/usr/bin/python
#    import psycopg2
#
#    conn = psycopg2.connect(
#    host="172.16.16.4",
#    database="default_db",
#    user="gen_user",
#    password="y0ebw5ucm1"
#  )