
server:
  port: 5000

spring:
  profiles:
    active: spring.profiles.active
  datasource:
    url: jdbc:postgresql://breadshop.covlrpaggjpn.us-east-1.rds.amazonaws.com:5432/breadshop
    username: postgres
    password: sardor2003