server:
  port: 8088
spring:
  profiles:
    active: spring.profiles.active
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Tashkent
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/bread_shop
    password: sardor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
app:
  name: Demo Bread Shop
  version: 1.0
  # spring.jpa.database-platform = org.hibernate.dialect.PostgreSQL94Dialect
  # spring.jpa.show-sql = false
  # spring.jpa.hibernate.ddl-auto = create-drop
  # spring.jpa.hibernate.naming.implicit-strategy = org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  # spring.jpa.properties.hibernate.format_sql=true